"""make_subscription_type_nullable

Revision ID: 0f4b623df300
Revises: 2078287d9abd
Create Date: 2025-09-12 20:38:23.398267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4b623df300'
down_revision: Union[str, Sequence[str], None] = '2078287d9abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'subscription_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'user_profiles', ['profile_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'subscription_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
