"""add_audio_storage_fields_to_voice_lines

Revision ID: 1d3bb28d0c1b
Revises: 21ee4da0f7e1
Create Date: 2025-08-19 18:59:27.156101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3bb28d0c1b'
down_revision: Union[str, Sequence[str], None] = '21ee4da0f7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # storage_url already exists from initial migration (255 chars), extend it to 500
    op.alter_column('voice_lines', 'storage_url', 
                   type_=sa.String(length=500),
                   existing_type=sa.String(length=255))
    
    # Add the new storage_path column
    op.add_column('voice_lines', sa.Column('storage_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_lines', 'storage_path')
    # Revert storage_url back to original length
    op.alter_column('voice_lines', 'storage_url',
                   type_=sa.String(length=255),
                   existing_type=sa.String(length=500))
    # ### end Alembic commands ###