"""add_order_index_to_voice_lines

Revision ID: 21ee4da0f7e1
Revises: 43a6f0871b23
Create Date: 2025-08-19 16:15:36.453325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ee4da0f7e1'
down_revision: Union[str, Sequence[str], None] = '43a6f0871b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_lines', sa.Column('order_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_lines', 'order_index')
    # ### end Alembic commands ###
