"""initial schema

Revision ID: 3504d33ce848
Revises: 
Create Date: 2025-08-27 16:20:43.300431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3504d33ce848'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', 'GERMAN', name='languageenum'), nullable=False),
    sa.Column('preferred_voice_id', sa.String(length=100), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('scenario_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('is_not_safe_reason', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('voice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('OPENING', 'QUESTION', 'RESPONSE', 'CLOSING', name='voicelinetypeenum'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_line_audios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voice_line_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.Enum('MULTILINGUAL_V2', 'TURBO_V2_5', 'FLASH_V2_5', 'ELEVEN_TTV_V3', name='elevenlabsmodelenum'), nullable=False),
    sa.Column('voice_settings', sa.JSON(), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('settings_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='voicelineaudiostatusenum'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_line_id'], ['voice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_line_audios_content_hash'), 'voice_line_audios', ['content_hash'], unique=False)
    op.create_index(op.f('ix_voice_line_audios_text_hash'), 'voice_line_audios', ['text_hash'], unique=False)
    op.create_index(op.f('ix_voice_line_audios_voice_line_id'), 'voice_line_audios', ['voice_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_line_audios_voice_line_id'), table_name='voice_line_audios')
    op.drop_index(op.f('ix_voice_line_audios_text_hash'), table_name='voice_line_audios')
    op.drop_index(op.f('ix_voice_line_audios_content_hash'), table_name='voice_line_audios')
    op.drop_table('voice_line_audios')
    op.drop_table('voice_lines')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
