"""Added Target Name to Scenario

Revision ID: 43a6f0871b23
Revises: 75208763de62
Create Date: 2025-08-18 22:10:58.616990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a6f0871b23'
down_revision: Union[str, Sequence[str], None] = '75208763de62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('target_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'target_name')
    # ### end Alembic commands ###
