"""add scenario_analysis json field to scenarios

Revision ID: 672105e844a5
Revises: 8729ebfa06c4
Create Date: 2025-08-25 12:33:55.583398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '672105e844a5'
down_revision: Union[str, Sequence[str], None] = '8729ebfa06c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('scenario_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'scenario_analysis')
    # ### end Alembic commands ###
