"""Change user_id to UUID for RLS compatibility

Revision ID: 75208763de62
Revises: d1ac6d7a65de
Create Date: 2025-08-18 21:36:03.572951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75208763de62'
down_revision: Union[str, Sequence[str], None] = 'd1ac6d7a65de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to properly cast VARCHAR to UUID
    op.execute("ALTER TABLE scenarios ALTER COLUMN user_id TYPE UUID USING user_id::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE scenarios ALTER COLUMN user_id TYPE VARCHAR(36) USING user_id::text")
    # ### end Alembic commands ###
