"""add voice_line_audios table and drop storage columns from voice_lines

Revision ID: 7b34ca5667fa
Revises: 1d3bb28d0c1b
Create Date: 2025-08-22 11:43:24.983163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b34ca5667fa'
down_revision: Union[str, Sequence[str], None] = '1d3bb28d0c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_line_audios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voice_line_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('model_id', sa.Enum('MULTILINGUAL_V2', 'TURBO_V2_5', 'FLASH_V2_5', 'ELEVEN_TTV_V3', name='elevenlabsmodelenum'), nullable=False),
    sa.Column('voice_settings', sa.JSON(), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('settings_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='voicelineaudiostatusenum'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_line_id'], ['voice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_line_audios_content_hash'), 'voice_line_audios', ['content_hash'], unique=False)
    op.create_index(op.f('ix_voice_line_audios_text_hash'), 'voice_line_audios', ['text_hash'], unique=False)
    op.create_index(op.f('ix_voice_line_audios_voice_line_id'), 'voice_line_audios', ['voice_line_id'], unique=False)
    op.drop_column('voice_lines', 'storage_path')
    op.drop_column('voice_lines', 'storage_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_lines', sa.Column('storage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('voice_lines', sa.Column('storage_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_voice_line_audios_voice_line_id'), table_name='voice_line_audios')
    op.drop_index(op.f('ix_voice_line_audios_text_hash'), table_name='voice_line_audios')
    op.drop_index(op.f('ix_voice_line_audios_content_hash'), table_name='voice_line_audios')
    op.drop_table('voice_line_audios')
    # ### end Alembic commands ###
