"""add preferred_voice_id to scenarios

Revision ID: 8729ebfa06c4
Revises: 7b34ca5667fa
Create Date: 2025-08-22 14:19:34.799893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8729ebfa06c4'
down_revision: Union[str, Sequence[str], None] = '7b34ca5667fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('preferred_voice_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'preferred_voice_id')
    # ### end Alembic commands ###
