"""add_next_billing_date_and_cancel_at_to_user_profiles

Revision ID: 9cffc3c9b0d3
Revises: 6a892f7830bb
Create Date: 2025-09-15 23:09:07.046492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cffc3c9b0d3'
down_revision: Union[str, Sequence[str], None] = '6a892f7830bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_call_log_id'), 'call_log', ['id'], unique=False)
    op.add_column('user_profiles', sa.Column('next_billing_date', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('cancel_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cancel_at')
    op.drop_column('user_profiles', 'next_billing_date')
    op.drop_index(op.f('ix_call_log_id'), table_name='call_log')
    # ### end Alembic commands ###
