"""add_conference_support_to_call_sessions

Revision ID: 9e0b21c2d653
Revises: a99febc0c1d7
Create Date: 2025-08-26 15:17:01.186153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0b21c2d653'
down_revision: Union[str, Sequence[str], None] = 'a99febc0c1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('conference_id', sa.String(length=100), nullable=True))
    op.add_column('call_sessions', sa.Column('webrtc_token', sa.String(length=500), nullable=True))
    op.add_column('call_sessions', sa.Column('conference_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_call_sessions_conference_id'), 'call_sessions', ['conference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_sessions_conference_id'), table_name='call_sessions')
    op.drop_column('call_sessions', 'conference_data')
    op.drop_column('call_sessions', 'webrtc_token')
    op.drop_column('call_sessions', 'conference_id')
    # ### end Alembic commands ###
