"""changed default for is_active flag

Revision ID: a5354dbfc6be
Revises: add_filler_to_enum
Create Date: 2025-09-02 15:52:33.103637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5354dbfc6be'
down_revision: Union[str, Sequence[str], None] = 'add_filler_to_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'scenarios',
        'is_active',
        existing_type=sa.Boolean(),
        server_default=sa.text('false'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'scenarios',
        'is_active',
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
