"""add_call_session_and_call_event_tables

Revision ID: a99febc0c1d7
Revises: 36b4c04da470
Create Date: 2025-08-25 18:30:32.736147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99febc0c1d7'
down_revision: Union[str, Sequence[str], None] = '36b4c04da470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('telnyx_call_id', sa.String(length=100), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'RINGING', 'ANSWERED', 'ACTIVE', 'COMPLETED', 'FAILED', 'CANCELLED', name='callstatusenum'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('machine_detection_result', sa.String(length=50), nullable=True),
    sa.Column('hangup_cause', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('telnyx_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_telnyx_call_id'), 'call_sessions', ['telnyx_call_id'], unique=True)
    op.create_index(op.f('ix_call_sessions_user_id'), 'call_sessions', ['user_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CALL_INITIATED', 'CALL_ANSWERED', 'CALL_HANGUP', 'CALL_MACHINE_DETECTION_ENDED', 'PLAYBACK_STARTED', 'PLAYBACK_ENDED', 'SPEAK_STARTED', 'SPEAK_ENDED', 'STREAMING_STARTED', 'STREAMING_STOPPED', name='calleventtypeenum'), nullable=False),
    sa.Column('telnyx_event_id', sa.String(length=100), nullable=True),
    sa.Column('voice_line_id', sa.Integer(), nullable=True),
    sa.Column('voice_line_audio_id', sa.Integer(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['voice_line_audio_id'], ['voice_line_audios.id'], ),
    sa.ForeignKeyConstraint(['voice_line_id'], ['voice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_session_id'), 'call_events', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_call_events_telnyx_event_id'), 'call_events', ['telnyx_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_telnyx_event_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_session_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_call_sessions_user_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_telnyx_call_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
