"""add background_image_url to scenario

Revision ID: cb9f040da5c6
Revises: 5c35799a44b4
Create Date: 2025-09-11 16:08:14.712869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9f040da5c6'
down_revision: Union[str, Sequence[str], None] = '5c35799a44b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('background_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'background_image_url')
    # ### end Alembic commands ###
